openapi: 3.0.3
info:
  title: Kardex API - Promedio Ponderado
  description: API para consulta de vista Kárdex con método de valoración promedio ponderado
  version: 1.0.0

servers:
  - url: /api
    description: API routes

paths:
  /kardex:
    get:
      summary: Consultar vista Kárdex de un ítem
      description: |
        Retorna el histórico de movimientos estilo Tarjeta Kárdex para un ítem específico,
        con columnas de Entradas, Salidas y Existencias (cantidad, P.U., valor).
      operationId: getKardex
      tags:
        - Kardex
      security:
        - bearerAuth: []
      parameters:
        - name: itemId
          in: query
          required: true
          description: ID del ítem a consultar
          schema:
            type: string
        - name: bodegaId
          in: query
          required: false
          description: ID de bodega (si no se especifica, muestra todas)
          schema:
            type: string
        - name: fechaDesde
          in: query
          required: false
          description: Fecha inicial del rango (ISO 8601)
          schema:
            type: string
            format: date
        - name: fechaHasta
          in: query
          required: false
          description: Fecha final del rango (ISO 8601)
          schema:
            type: string
            format: date
        - name: tipo
          in: query
          required: false
          description: Filtrar por tipo de movimiento
          schema:
            type: string
            enum: [entrada, salida, transferencia]
        - name: page
          in: query
          required: false
          description: Número de página (1-indexed)
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: pageSize
          in: query
          required: false
          description: Registros por página (máximo 100)
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 100
      responses:
        '200':
          description: Vista Kárdex del ítem
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KardexResponse'
        '400':
          description: Parámetros inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: No autenticado
        '403':
          description: Sin permisos (requiere movements:read)

  /kardex/export:
    get:
      summary: Exportar Kárdex a CSV
      description: Descarga el Kárdex completo de un ítem en formato CSV
      operationId: exportKardexCsv
      tags:
        - Kardex
      security:
        - bearerAuth: []
      parameters:
        - name: itemId
          in: query
          required: true
          description: ID del ítem a exportar
          schema:
            type: string
        - name: bodegaId
          in: query
          required: false
          schema:
            type: string
        - name: fechaDesde
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: fechaHasta
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: tipo
          in: query
          required: false
          schema:
            type: string
            enum: [entrada, salida, transferencia]
      responses:
        '200':
          description: Archivo CSV
          headers:
            Content-Disposition:
              schema:
                type: string
              example: attachment; filename="kardex-ITEM001-2026-01-16.csv"
          content:
            text/csv:
              schema:
                type: string
                example: |
                  Fecha,Detalle,N° Doc,Entrada Cant,Entrada P.U.,Entrada Valor,Salida Cant,Salida P.U.,Salida Valor,Exist. Cant,Exist. P.U.,Exist. Valor
                  2026-01-01,Inventario inicial,,,,,,,,120,500.0000,60000.0000
                  2026-01-02,Orden de compra,40,60,510.0000,30600.0000,,,,180,503.3333,90600.0000
        '400':
          description: Parámetros inválidos
        '401':
          description: No autenticado
        '403':
          description: Sin permisos

  /kardex/auditoria:
    get:
      summary: Consultar historial de cambios de costo promedio
      description: Retorna el log de auditoría de cambios en el costo promedio de un ítem
      operationId: getAuditoriaCosto
      tags:
        - Kardex
        - Auditoría
      security:
        - bearerAuth: []
      parameters:
        - name: itemId
          in: query
          required: true
          schema:
            type: string
        - name: bodegaId
          in: query
          required: false
          schema:
            type: string
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Historial de cambios de costo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditoriaResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    KardexResponse:
      type: object
      required:
        - data
        - pagination
        - item
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/KardexRow'
        pagination:
          $ref: '#/components/schemas/Pagination'
        item:
          $ref: '#/components/schemas/ItemInfo'
        resumen:
          $ref: '#/components/schemas/KardexResumen'

    KardexRow:
      type: object
      required:
        - fecha
        - detalle
        - existencia
      properties:
        fecha:
          type: string
          format: date-time
        detalle:
          type: string
          description: Descripción del movimiento
        numeroDocumento:
          type: string
          nullable: true
        entrada:
          $ref: '#/components/schemas/KardexMovement'
        salida:
          $ref: '#/components/schemas/KardexMovement'
        existencia:
          $ref: '#/components/schemas/KardexExistencia'
        movimientoId:
          type: string
          description: ID del movimiento para navegación

    KardexMovement:
      type: object
      nullable: true
      properties:
        cantidad:
          type: number
          format: decimal
          example: 60.0000
        precioUnitario:
          type: number
          format: decimal
          example: 510.0000
        valor:
          type: number
          format: decimal
          example: 30600.0000

    KardexExistencia:
      type: object
      required:
        - cantidad
        - costoPromedio
        - valor
      properties:
        cantidad:
          type: number
          format: decimal
          example: 180.0000
        costoPromedio:
          type: number
          format: decimal
          example: 503.3333
        valor:
          type: number
          format: decimal
          example: 90600.0000

    KardexResumen:
      type: object
      properties:
        totalEntradas:
          type: number
        totalSalidas:
          type: number
        existenciaFinal:
          type: number
        valorFinal:
          type: number
        costoPromedioActual:
          type: number

    ItemInfo:
      type: object
      properties:
        id:
          type: string
        codigo:
          type: string
        nombre:
          type: string
        unidadMedida:
          type: string
        categoria:
          type: string
          nullable: true

    AuditoriaResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/AuditoriaRow'
        pagination:
          $ref: '#/components/schemas/Pagination'

    AuditoriaRow:
      type: object
      properties:
        id:
          type: string
        fecha:
          type: string
          format: date-time
        usuario:
          type: string
        movimientoId:
          type: string
        costoAnterior:
          type: number
        costoNuevo:
          type: number
        cantidadAnterior:
          type: number
        cantidadNueva:
          type: number
        diferenciaCosto:
          type: number
          description: costoNuevo - costoAnterior

    Pagination:
      type: object
      required:
        - page
        - pageSize
        - total
        - totalPages
      properties:
        page:
          type: integer
        pageSize:
          type: integer
        total:
          type: integer
        totalPages:
          type: integer

    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
        details:
          type: object
