import {
  IconArrowsExchange,
  IconBox,
  IconBuildingWarehouse,
  IconClipboardList,
  IconTag,
  IconFileImport,
  IconLayoutDashboard,
  IconReportAnalytics,
  IconUsers,
} from "@tabler/icons-react"

import type { NavigationDefinition } from "./types"

export const panelNavigation: NavigationDefinition = {
  sections: [
    {
      id: "principal",
      label: "Principal",
      order: 1,
      isCollapsible: false,
      items: [
        {
          id: "dashboard",
          label: "Dashboard",
          href: "/dashboard",
          order: 1,
          sectionId: "principal",
          requiredRoles: ["admin", "bodeguero"],
          icon: IconLayoutDashboard,
        },
        {
          id: "kardex",
          label: "Kardex",
          href: "/kardex",
          order: 2,
          sectionId: "principal",
          requiredRoles: ["admin", "bodeguero"],
          icon: IconReportAnalytics,
        },
      ],
    },
    {
      id: "movimientos",
      label: "Movimientos",
      order: 2,
      isCollapsible: false,
      items: [
        {
          id: "movements",
          label: "Movimientos",
          href: "/movements",
          order: 1,
          sectionId: "movimientos",
          requiredRoles: ["admin", "bodeguero"],
          icon: IconArrowsExchange,
        },
      ],
    },
    {
      id: "catalogos",
      label: "Catalogos",
      order: 3,
      isCollapsible: true,
      items: [
        {
          id: "items",
          label: "Items",
          href: "/items",
          order: 1,
          sectionId: "catalogos",
          requiredRoles: ["admin", "bodeguero"],
          icon: IconBox,
        },
        {
          id: "categories",
          label: "Categorias",
          href: "/categories",
          order: 2,
          sectionId: "catalogos",
          requiredRoles: ["admin", "bodeguero"],
          icon: IconTag,
        },
        {
          id: "items-import",
          label: "Importar items",
          href: "/items/import",
          order: 3,
          sectionId: "catalogos",
          requiredRoles: ["admin"],
          icon: IconFileImport,
        },
        {
          id: "third-parties",
          label: "Terceros",
          href: "/third-parties",
          order: 4,
          sectionId: "catalogos",
          requiredRoles: ["admin", "bodeguero"],
          icon: IconUsers,
        },
        {
          id: "warehouses",
          label: "Bodegas",
          href: "/warehouses",
          order: 5,
          sectionId: "catalogos",
          requiredRoles: ["admin", "bodeguero"],
          icon: IconBuildingWarehouse,
        },
      ],
    },
    {
      id: "configuracion",
      label: "Configuracion",
      order: 4,
      isCollapsible: true,
      items: [
        {
          id: "settings-users",
          label: "Usuarios",
          href: "/settings/users",
          order: 1,
          sectionId: "configuracion",
          requiredRoles: ["admin"],
          icon: IconUsers,
        },
        {
          id: "settings-audit",
          label: "Auditoria",
          href: "/settings/audit-log",
          order: 2,
          sectionId: "configuracion",
          requiredRoles: ["admin"],
          icon: IconClipboardList,
        },
      ],
    },
  ],
}
